### ISSUE TITLE
{cpu1} displays 0% all the time. label:bug

### ISSUE THREAD

**Issue by SteveGuo** [fossfreedom/indicator-sysmonitor#23]
{cpu1} displays always 0% when set to display two cpu cores like this: {cpu0}{cpu1}

    def _fetch_cpu(self, percpu=False):
        if percpu:
        return ps.cpu_percent(interval=0, percpu=True)

Here psutil.cpu_percent is called twice almost simultaneously which means time between the first call and the second call is too short to measure the {cpu1} utilization.

I suggest that provide an option like {cpuall} to display all the cpu cores and call the psutil.cpu_percent only once per update.

**Comment by fossfreedom** [comment]
not sure about the premise of two simultaneous calls being made.

Looking at that function it seems to be trying to produce an average value - not a per CPU value.

Looking back at the original source (https://github.com/fossfreedom/indicator-sysmonitor/commit/c835ee928198961a61ab15160fb0174b45fc993d) before the fork, don't think a per CPU was possible - doesnt look like it was coded to do this correctly.

I'm a little busy at the moment to work on this - working full time on another two projects.  Feel free to dabble - pull request etc.

Otherwise, I'll get to this as and when.

**Comment by SteveGuo** [comment]
OK, pull request https://github.com/fossfreedom/indicator-sysmonitor/pull/24
Tested under Ubuntu 15.04

**Comment by SteveGuo** [comment]
Bug fixed, close this issue.
