### ISSUE TITLE
absolute the Formmat

### ISSUE THREAD

**Issue by RanchoCooper** [fossfreedom/indicator-sysmonitor#57]
I think it would be better if Format the outpus

i.e:
     {net}
sometimes are like "xxxKB/s, xxxKB/s"
sometime               "xxb/s, xx/bs"

in other word, the length of outpus may change due to network variable

if the width is absolute, will be better
##

**Comment by fossfreedom** [comment]
Sounds like a good idea.  Happy to consider any patches for this.

**Comment by RanchoCooper** [comment]
thanks for reading : )

**Comment by illpillow** [comment]
I was thinking about the same and managed to reduce most of the bouncing by editing sensors.py. If anyone of you is interested in the solution, here it is:

(1) Since I am not interested in bytes at all, I removed the unit from the list. You can also change it to something that has same width as the others units have (i.e. BB).
```python
B_UNITS = ['KB', 'MB', 'GB', 'TB']
```

(2) If you removed the unit, you need to convert the bytes to kilobytes all the time, so divide it by 1024 as it would have done before.
```python
def bytes_to_human(bytes_):
    unit = 0
    bytes_ /= 1024
    while bytes_ > 1024:
        unit += 1
        bytes_ /= 1024
```

(3) Finally add a string format to pad the number always to 3 or 4 numbers (i.e. 0:03d or 0:04d).
```python
return '{0:03d}{1}'.format(int(bytes_), B_UNITS[unit])
```

**Comment by mannfuri** [comment]
`s
        def bytes_to_human_custome(n):
            if n < 1000:
                return "{}B".format(int(n))
            elif n < 1000 * 1000:
                return "{}K".format(int(n / 1000))
            elif n < 1000 * 1000 * 1000:
                return "{}M".format(int(n / 1000 / 1000))
            else:
                return "{}G".format(int(n / 1000 / 1000 / 1000))

        return "↓{:>2s} ↑{:>2s}".format(
            bytes_to_human_custome(current[0]), bytes_to_human_custome(current[1])
        )`

my version
