### ISSUE TITLE
wrong/still indication with ubuntu 17.10 Gnome

### ISSUE THREAD

**Issue by alex1sc** [fossfreedom/indicator-sysmonitor#75]
Just upgrade the to the new 17.10 on my asus laptop and indications are wrong/still after a while. Enclosed screenshot. Was working fine until upgrade from 17.04 and unity. 
![screenshot from 2017-10-24 11-38-33](https://user-images.githubusercontent.com/19567601/31935756-e85cd674-b8af-11e7-80b8-5293bc7b0e1c.png)

**Comment by fossfreedom** [comment]
All the calculations are done in this module: https://github.com/fossfreedom/indicator-sysmonitor/blob/master/sensors.py

feel free to dig in a let me know what needs changing.

**Comment by fossfreedom** [comment]
ok - I have seen linus torvalds comment on the latest changes in the kernel 4.14 rc8 - the kernel 4.13 in 17.10 is buggy and doesnt report CPU stuff correctly.  This is now fixed in kernel 4.14.

As such - this is an upstream matter and will be resolved if you upgrade to the latest kernel or use a later kernel as part of 18.04.
