### ISSUE TITLE
Only blank space in fresh Xubuntu 18.04.1

### ISSUE THREAD

**Issue by nils-se** [fossfreedom/indicator-sysmonitor#91]
Hey,

nice work, love your indicator and have been using it for a couple of installations.

I am currently on a fresh installation of Xubuntu 18.04.1 and there is only a bit of blank space if I start the indicator. Is there some dependencie I am missing? I installed from your ppa. Version is 0.8.2.

If I hover over the indicator it shows me the desired output in a tooltip.

![indicator_tooltip](https://user-images.githubusercontent.com/24794243/50272884-6a9f9100-0439-11e9-9823-d79a70c5b590.png)

![indicator_sysmonitor_screenshit](https://user-images.githubusercontent.com/24794243/50272885-6a9f9100-0439-11e9-84e1-560eb964c7b8.png)
Starting in terminal only shows:
```
INFO:root:start
INFO:root:Menu shown
INFO:root:Fetcher started
```

Any ideas where to look for the cause?

**Comment by fossfreedom** [comment]
hmm.  The indicator uses the label part of an appindicator.  The icon displayed is basically a hidden 1px icon.

So does xubuntu have a way to turn labels on / off for appindicators?

**Comment by fossfreedom** [comment]
I'm not familiar with the xfce statusnotifier plugin but from a quick google there appears to be various issues about its support for appindicators - e.g. this one https://bugs.launchpad.net/ubuntu/+source/xfce4-statusnotifier-plugin/+bug/1756627

I'm guessing statusnotifier icons presents label information in a different way - I'm assuming statusnotifier icons can also display labels.  Assuming they do support labels maybe a code change is required to

a) understand that it is being displayed by a statusnotifier plugin
b) use a statusnotifier label

Since this is XFCE specific hopefully someone who runs this environment can confirm and supply a pull-request to resolve

**Comment by nils-se** [comment]
Thank you for the pointers! 

Some more information: I ran xfce4 on top of a ubuntu budgie installation and it worked with indicator-sysmonitor. Maybe some dependencies missing in xubuntu? Hope someone will stumble upon this issue ;)

**Comment by KYatoo** [comment]
Same problem in Manjaro. (2022/1/14)
